Task completed
itmo-java-basics-2020/task-3-hashtable-classes-inner-classes-class-object-YahimaB pull request #1
Opened 2020-03-13 23:51 UTC by YahimaB

2020-03-22 17:04 UTC, AfanasievYuriy requested changes

2020-03-22 17:04 UTC, AfanasievYuriy commented on src/main/java/ru/itmo/java/HashTable.java
> +
пустые строки в кол-ве > 1 все же перебор

2020-03-22 17:04 UTC, AfanasievYuriy commented on src/main/java/ru/itmo/java/HashTable.java
> +    protected class HashNode {
решение сделать его protected сможешь объяснить?)

2020-03-22 18:05 UTC, YahimaB reviewed
Ответы на вопросы

2020-03-22 18:05 UTC, YahimaB commented on src/main/java/ru/itmo/java/HashTable.java
> +
Мне так удобней отделять функции от переменных. Ибо во время реализации того же интерфейса, не всматриваясь, так гораздо проще определить где что начинается.

2020-03-22 18:05 UTC, YahimaB commented on src/main/java/ru/itmo/java/HashTable.java
> +    protected class HashNode {
https://docs.oracle.com/javase/tutorial/java/javaOO/accesscontrol.html
Мне не нужно, чтобы снаружи кто-то мог отдельно использовать этот класс => НЕ public
Мне нужно, чтобы наследники ХэшТаблицы (в том числе и не из нашего пакета) могли тоже использовать этот класс => НЕ private и не package-private
Вывод => protected

2020-03-23 00:17 UTC, AfanasievYuriy commented on src/main/java/ru/itmo/java/HashTable.java
> +
> Мне так удобней отделять функции от переменных. Ибо во время реализации того же интерфейса, не всматриваясь, так гораздо проще определить где что начинается.

Это здорово что тебе удобно, но твой код еще потом кому-то читать (в данном случае этот кто-то - я)

2020-03-23 00:18 UTC, AfanasievYuriy commented on src/main/java/ru/itmo/java/HashTable.java
> +    protected class HashNode {
принято

2020-03-23 00:28 UTC, AfanasievYuriy commented
> Ответы на вопросы

Не нужно выносить ответы на комментарии в отдельный блок пулл реквеста - просто ответов на мои комментарии достаточно. Да это и не "ответы на вопросы" в контексте студент-преподаватель. Мы тут ревью проходим точно такое же как на любом настоящем коммерческом (и не только) проекте

2020-04-07 04:56 UTC, closed without merging